[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'modules/chainsafe',
    'runtime/metaverse',
    'runtime/pioneer',
    'runtime/tewai',
    'primitives/evm',
    'primitives/metaverse',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'pallet/evm'
]
