[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'runtime/pioneer',
    'runtime/metaverse',
    'runtime/integration-tests',
    'primitives/metaverse',
    'modules/relaychain',
    'modules/support',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'pallet/evm',
    'pallet/evm/*',
    'primitives/evm/',
    'modules/chainsafe',
]

[patch.crates-io]
ethereum = { git = "https://github.com/justinphamnz/ethereum", branch = "polkadot-v0.9.22" }
evm = { git = "https://github.com/justinphamnz/evm", branch = "master" }
evm-gasometer = { git = "https://github.com/justinphamnz/evm", branch = "master" }
evm-runtime = { git = "https://github.com/justinphamnz/evm", branch = "master" }