[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'bitcountry-runtime'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

pallet-aura = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-collective = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
pallet-grandpa = { version = "2.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false }
pallet-sudo = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-timestamp = { version = "2.0.0", default-features = false }
pallet-transaction-payment = { version = "2.0.0", default-features = false }
pallet-treasury = { version = "2.0.0", default-features = false }
frame-executive = { version = "2.0.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false }
sp-block-builder = { version = "2.0.0", default-features = false }
sp-consensus-aura = { version = "0.8.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-inherents = { version = "2.0.0", default-features = false }
sp-offchain = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-session = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-transaction-pool = { version = "2.0.0", default-features = false }
sp-version = { version = "2.0.0", default-features = false }

# Used for the node's RPCs
frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0", default-features = false }

# Orml pacakges
orml-currencies = { default-features = false, version = '0.3.0' }
orml-tokens = { default-features = false, version = '0.3.0' }

# Contracts specific packages
pallet-contracts = { version = "2.0.0", default_features = false }
pallet-contracts-primitives = { version = "2.0.0", default_features = false }
pallet-contracts-rpc-runtime-api = { version = "0.8.0", default-features = false }
oracle = {version = "1.0.0", path = "../pallets/oracle", default_features= false}

primitives = { package = "bit-country-primitives", path = "../pallets/primitives", default-features = false }

[dependencies.unique-asset]
default-features = false
package = 'pallet-unique-asset'
path = '../pallets/uniqueAsset'
version = '2.0.0-rc6'

[dependencies.country]
default-features = false
package = 'pallet-country'
path = '../pallets/country'
version = '2.0.0-rc6'

[dependencies.block]
default-features = false
package = 'pallet-block'
path = '../pallets/block'
version = '2.0.0-rc6'

[dependencies.section]
default-features = false
package = 'pallet-section'
path = '../pallets/section'
version = '2.0.0-rc6'

[dependencies.tokenization]
default-features = false
package = 'pallet-tokenization'
path = '../pallets/tokenization'
version = '2.0.0-rc6'

[dependencies.nft]
default-features = false
package = 'pallet-nft'
path = '../pallets/nft'
version = '2.0.0-rc6'

[dependencies.auction]
default-features = false
package = 'pallet-auction'
path = '../pallets/auction'
version = '2.0.0-rc6'


[build-dependencies]
wasm-builder-runner = { version = "1.0.6", package = "substrate-wasm-builder-runner" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-collective/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-treasury/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'primitives/std',
    'orml-currencies/std',
    'orml-tokens/std',
    'unique-asset/std',
    'country/std',
    'block/std',
    'section/std',
    'nft/std',
    'auction/std',
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts-rpc-runtime-api/std",
    "oracle/std"
]

