[package]
name = "bitcountry-staking"
version = "3.0.0"
authors = ["Bit.Country Developers <genesis@bit.country>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://bit.country"
repository = "https://github.com/paritytech/substrate/"
description = "Bit.Country staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "3.0.0", default-features = false}
sp-npos-elections = { version = "3.0.0", default-features = false}
sp-io ={ version = "3.0.0", default-features = false}
sp-runtime = { version = "3.0.0", default-features = false}
sp-staking = { version = "3.0.0", default-features = false}
frame-support = { version = "3.0.0", default-features = false}
frame-system = { version = "3.0.0", default-features = false}
pallet-session = { version = "3.0.0", default-features = false, features = ["historical"]}
pallet-authorship = { version = "3.0.0", default-features = false}
sp-application-crypto = { version = "3.0.0", default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { version = "3.0.0", default-features = false, optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
sp-core = { version = "3.0.0"}
sp-storage = { version = "3.0.0"}
sp-tracing = { version = "3.0.0"}
pallet-balances = { version = "3.0.0"}
pallet-timestamp = { version = "3.0.0" }
pallet-staking-reward-curve = { version = "3.0.0" }
substrate-test-utils = { version = "3.0.0"}
frame-benchmarking = { version = "3.0.0" }
rand_chacha = { version = "0.2" }
parking_lot = "0.11.1"
hex = "0.4"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-npos-elections/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]