#Metaverse Parachain runtime - need to merge rococo branch back to this runtime
[package]
authors = ["Metaverse.Network & Bit.Country Developers <https://github.com/bit-country>"]
edition = '2021'
homepage = "https://metaverse.network"
license = "Unlicense"
name = "metaverse-runtime"
description = "Metaverse Runtime"
repository = "https://github.com/bit-country/Metaverse-Network"
version = "0.0.60"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, package = "parity-scale-codec" }
serde = { workspace = true, optional = true, default-features = false }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
scale-info = { workspace = true }
hex-literal = { workspace = true }
getrandom = { workspace = true }

pallet-aura = { workspace = true }
pallet-balances = { workspace = true }
frame-support = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-insecure-randomness-collective-flip = { workspace = true }
pallet-sudo = { workspace = true }
pallet-collective = { workspace = true }
pallet-vesting = { workspace = true }
frame-system = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
frame-executive = { workspace = true }

sp-api = { workspace = true }
sp-io = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-weights = { workspace = true }

pallet-authorship = { workspace = true }
pallet-session = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-democracy = { workspace = true }
pallet-utility = { workspace = true }
pallet-preimage = { workspace = true }
pallet-membership = { workspace = true }
pallet-treasury = { workspace = true }
pallet-collator-selection = { workspace = true }
pallet-proxy = { workspace = true }

frame-try-runtime = { workspace = true, optional = true }
try-runtime-cli = { workspace = true, optional = true }
polkadot-primitives = { workspace = true }

# Used for the node template"s RPCs
frame-system-rpc-runtime-api = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }

# Used for runtime benchmarking
frame-benchmarking = { workspace = true, optional = true }
frame-system-benchmarking = { workspace = true, optional = true }

# EVM pallets
pallet-evm = { workspace = true }
pallet-evm-chain-id = { workspace = true }
pallet-ethereum = { workspace = true }
pallet-base-fee = { workspace = true }
fp-self-contained = { workspace = true }
fp-rpc = { workspace = true }
fp-evm = { workspace = true }

# external crates - orml packages
orml-currencies = { workspace = true }
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
orml-nft = { workspace = true }
orml-oracle = { workspace = true }
orml-rewards = { workspace = true }
orml-benchmarking = { workspace = true, optional = true }
# metaverse dependencies
primitives = { package = "bit-country-primitives", path = "../../primitives/metaverse", default-features = false }
auction-manager = { package = "auction-manager", path = "../../traits/auction-manager", default-features = false }
metaverse = { package = "pallet-metaverse", path = "../../pallets/metaverse", default-features = false }
estate = { package = "pallet-estate", path = "../../pallets/estate", default-features = false }
nft = { package = "pallet-nft", path = "../../pallets/nft", version = "2.0.0-rc6", default-features = false }
continuum = { package = "pallet-continuum", path = "../../pallets/continuum", version = "0.0.1", default-features = false }
auction = { package = "pallet-auction", path = "../../pallets/auction", version = "2.0.0-rc6", default-features = false }
currencies = { package = "currencies", path = "../../pallets/currencies", version = "2.0.0-rc6", default-features = false }
mining = { package = "pallet-mining", path = "../../pallets/mining", version = "2.0.0-rc6", default-features = false }
reward = { package = "pallet-reward", path = "../../pallets/reward", version = "2.0.0-rc6", default-features = false }
governance = { package = "pallet-governance", path = "../../pallets/governance", version = "2.0.0-rc6", default-features = false }
crowdloan = { package = "pallet-crowdloan", path = "../../pallets/crowdloan", version = "2.0.0-rc6", default-features = false }
economy = { package = "pallet-economy", path = "../../pallets/economy", version = "2.0.0-rc6", default-features = false }
emergency = { package = "pallet-emergency", path = "../../pallets/emergency", version = "2.0.0-rc6", default-features = false }
core-primitives = { path = "../../traits/core-primitives", default-features = false }
metaverse-runtime-common = { path = "../common", default-features = false }
asset-manager = { path = "../../pallets/asset-manager", default-features = false }
evm-mapping = { package = "pallet-evm-mapping", path = "../../pallets/evm-mapping", default-features = false }
spp = { package = "pallet-spp", path = "../../pallets/spp", default-features = false }

modules-bridge = { path = "../../modules/bridge", default-features = false }

# ink! contracts pacakges
pallet-contracts = { workspace = true }
pallet-contracts-primitives = { workspace = true }

# XCM builder ( need to be used to build the runtime benchmarking correctly)
xcm-builder = { workspace = true }

# Cumulus Dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-pallet-session-benchmarking = { workspace = true }
parachain-info = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "scale-info/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "pallet-aura/std",
    "pallet-balances/std",
    "pallet-collective/std",
    "pallet-grandpa/std",
    "pallet-insecure-randomness-collective-flip/std",
    "pallet-sudo/std",
    "pallet-session/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-transaction-payment/std",
    "pallet-vesting/std",
    "pallet-authorship/std",
    "pallet-scheduler/std",
    "pallet-democracy/std",
    "pallet-preimage/std",
    "pallet-membership/std",
    "pallet-treasury/std",
    "pallet-proxy/std",
    "sp-api/std",
    "xcm-builder/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-weights/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "auction-manager/std",
    "orml-currencies/std",
    "orml-tokens/std",
    "orml-nft/std",
    "orml-oracle/std",
    "orml-rewards/std",
    "primitives/std",
    "metaverse/std",
    "auction/std",
    "estate/std",
    "nft/std",
    "continuum/std",
    "currencies/std",
    "mining/std",
    "reward/std",
    "governance/std",
    "crowdloan/std",
    "economy/std",
    "emergency/std",
    "evm-mapping/std",
    "spp/std",
    "pallet-utility/std",
    "pallet-collator-selection/std",
    "orml-benchmarking/std",
    "pallet-base-fee/std",
    "fp-self-contained/std",
    "fp-rpc/std",
    "fp-evm/std",
    "pallet-ethereum/std",
    "pallet-evm/std",
    "pallet-evm-chain-id/std",
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "frame-try-runtime/std",
    "metaverse-runtime-common/std",
    "modules-bridge/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-xcmp-queue/std",
    "cumulus-pallet-xcm/std",
    "cumulus-primitives-core/std",
    "cumulus-primitives-timestamp/std",
    "cumulus-primitives-utility/std",
]
runtime-benchmarks = [
    "xcm-builder/runtime-benchmarks",
    "orml-benchmarking",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "nft/runtime-benchmarks",
    "estate/runtime-benchmarks",
    "emergency/runtime-benchmarks",
    "currencies/runtime-benchmarks",
    "auction/runtime-benchmarks",
    "metaverse/runtime-benchmarks",
    "crowdloan/runtime-benchmarks",
    "reward/runtime-benchmarks",
    "economy/runtime-benchmarks",
    "mining/runtime-benchmarks",
    "evm-mapping/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-ethereum/runtime-benchmarks"
]

disable-runtime-api = []

try-runtime = [
    "try-runtime-cli",
    "frame-executive/try-runtime",
    "frame-try-runtime",
    "frame-system/try-runtime",
]