[package]
name = "bit-country-primitives"
version = "0.1.0"
authors = ["Metaverse.Network & Bit.Country Developers"]
edition = '2021'

[dependencies]
serde = { version = "1.0.137", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1", default-features = false, features = ["derive"] }
hex-literal = "0.3.1"
num_enum = { version = "0.5.3", default-features = false }
ethabi = { version = "17.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24", default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "scale-info/std",
    "ethabi/std",
    "frame-system/std",
    "frame-support/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "xcm/std"
]