[package]
name = "bit-country-primitives"
version = "0.1.0"
authors = ["Metaverse.Network & Bit.Country Developers"]
edition = '2021'

[dependencies]
serde = { workspace = true, optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
scale-info = { workspace = true }
hex-literal = { workspace = true }
num_enum = { workspace = true }
ethabi = { workspace = true }
sp-core = { workspace = true }
frame-system = { workspace = true }
frame-support = { workspace = true }
sp-application-crypto = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
xcm = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "scale-info/std",
    "ethabi/std",
    "frame-system/std",
    "frame-support/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "xcm/std"
]