[package]
authors = ['Metaverse Network <https://github.com/bit-country>']
description = 'Metaverse Network pallet for auction management.'
edition = '2021'
homepage = 'https://metaverse.network'
license = 'Unlicense'
name = 'auction-manager'
repository = 'https://github.com/bit-country'
version = '2.0.0-rc6'

[dependencies]
serde = { version = "1.0.140", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
frame-support = { workspace = true }
# Used for the node's RPCs
primitives = { package = "bit-country-primitives", path = "../../primitives/metaverse", default-features = false }

funty = { workspace = true }
scale-info = { workspace = true }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'frame-support/std',
]