[package]
name = "pioneer-runtime"
description = "Pioneer Runtime"
version = "0.0.7"
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
substrate-wasm-builder = { workspace = true, default-features = true }

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.1.5', default-features = false, features = ['derive'] }
log = { workspace = true }
serde = { workspace = true, optional = true, features = ['derive'] }
scale-info = { workspace = true }
smallvec = { workspace = true }
hex-literal = { workspace = true }
getrandom = { workspace = true }

# external crates - orml packages
orml-currencies = { workspace = true }
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
orml-nft = { workspace = true }
orml-unknown-tokens = { workspace = true }
orml-xtokens = { workspace = true }
orml-xcm = { workspace = true }
orml-xcm-support = { workspace = true }
orml-oracle = { workspace = true }
# Metaverse Dependencies
primitives = { package = 'bit-country-primitives', path = '../../primitives/metaverse', default-features = false }
metaverse = { package = 'pallet-metaverse', path = '../../pallets/metaverse', default-features = false }
currencies = { package = 'currencies', path = '../../pallets/currencies', version = '2.0.0-rc6', default-features = false }
nft = { package = 'pallet-nft', path = '../../pallets/nft', version = '2.0.0-rc6', default-features = false }
auction = { package = 'pallet-auction', path = '../../pallets/auction', version = '2.0.0-rc6', default-features = false }
continuum = { package = 'pallet-continuum', path = '../../pallets/continuum', version = '0.0.1', default-features = false }
mining = { package = 'pallet-mining', path = '../../pallets/mining', version = '2.0.0-rc6', default-features = false }
estate = { package = 'pallet-estate', path = '../../pallets/estate', default-features = false }
crowdloan = { package = "pallet-crowdloan", path = "../../pallets/crowdloan", version = "2.0.0-rc6", default-features = false }
economy = { package = "pallet-economy", path = "../../pallets/economy", version = "2.0.0-rc6", default-features = false }
emergency = { package = "pallet-emergency", path = "../../pallets/emergency", version = "2.0.0-rc6", default-features = false }
core-primitives = { path = "../../traits/core-primitives", default-features = false }
asset-manager = { path = "../../pallets/asset-manager", default-features = false }
reward = { package = "pallet-reward", path = "../../pallets/reward", version = "2.0.0-rc6", default-features = false }
modules-bridge = { path = "../../modules/bridge", default-features = false }

## Substrate Primitive Dependencies
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-core = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }

## Substrate FRAME Dependencies
frame-executive = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }

## Substrate Pallet Dependencies
pallet-aura = { workspace = true }
pallet-balances = { workspace = true }
pallet-collective = { workspace = true }
pallet-democracy = { workspace = true }
pallet-randomness-collective-flip = { workspace = true }
pallet-sudo = { workspace = true }
pallet-multisig = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-vesting = { workspace = true }
pallet-authorship = { workspace = true }
pallet-session = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-utility = { workspace = true }
pallet-bounties = { workspace = true }
pallet-preimage = { workspace = true }
pallet-membership = { workspace = true }
pallet-proxy = { workspace = true }

# Cumulus Dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-pallet-session-benchmarking = { workspace = true }
parachain-info = { workspace = true }
pallet-collator-selection = { workspace = true }

# Polkadot Dependencies
polkadot-parachain = { workspace = true }
polkadot-primitives = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
pallet-xcm = { workspace = true }
polkadot-runtime-common = { workspace = true }
metaverse-runtime-common = { path = "../common", default-features = false }

[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking',
    'sp-runtime/runtime-benchmarks',
    "xcm-builder/runtime-benchmarks",
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    "pallet-collator-selection/runtime-benchmarks",
    'pallet-timestamp/runtime-benchmarks',
    "pallet-xcm/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "cumulus-pallet-session-benchmarking/runtime-benchmarks",
]

std = [
    "codec/std",
    "scale-info/std",
    "serde",
    "log/std",
    "sp-api/std",
    "sp-std/std",
    "sp-io/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-version/std",
    "sp-offchain/std",
    "sp-session/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "frame-support/std",
    "frame-executive/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-randomness-collective-flip/std",
    "pallet-timestamp/std",
    "pallet-sudo/std",
    "pallet-transaction-payment/std",
    "pallet-collective/std",
    "pallet-session/std",
    "pallet-scheduler/std",
    "pallet-vesting/std",
    "pallet-authorship/std",
    "pallet-multisig/std",
    "pallet-membership/std",
    "pallet-utility/std",
    "pallet-proxy/std",
    "parachain-info/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-xcmp-queue/std",
    "cumulus-pallet-xcm/std",
    "cumulus-primitives-core/std",
    "cumulus-primitives-timestamp/std",
    "cumulus-primitives-utility/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "pallet-aura/std",
    "sp-consensus-aura/std",
    'orml-tokens/std',
    'orml-nft/std',
    "orml-oracle/std",
    "orml-xtokens/std",
    'primitives/std',
    'metaverse/std',
    'currencies/std',
    'nft/std',
    'auction/std',
    'continuum/std',
    'mining/std',
    'estate/std',
    'crowdloan/std',
    "economy/std",
    "emergency/std",
    "asset-manager/std",
    "reward/std",
    'pallet-collator-selection/std',
    "pallet-preimage/std",
    "metaverse-runtime-common/std",
    "modules-bridge/std"
]
