name: Publish Release

# This script is used to build and publish the release WASM build of runtime:
# - Checkout the selected branch
# - Build WASM using Substrate Runtime Tool

env:
  SUBWASM_VERSION: 0.15.0

on:
  workflow_dispatch:
    inputs:
      # Get name of the chain
      chain:
        description: Chain Runtime (default = pioneer)
        required: true
        default: pioneer
        type: choice
        options:
          - metaverse
          - pioneer
      # Get the SR Tool image used to build
      srtool_image:
        description: Default to use the latest. You can use an alternate image, use with caution!
        required: false

jobs:
  srtool:
    name: Build and publish ${{ github.event.inputs.chain }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the Bit.Country codebase
      - name: Checkout Codebase
        uses: actions/checkout@v2

      # Build WASM with Substrate Runtime Tool
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: ${{ github.event.inputs.chain }}
          tag: ${{ github.event.inputs.srtool_image }}

      # Output the build summary
      - name: Build Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ github.event.inputs.chain }}-srtool-digest.json
          cat ${{ github.event.inputs.chain }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
          echo "Compressed Runtime: ${{ steps.srtool_build.outputs.wasm_compressed }}"

      # it takes a while to build the runtime, so let's save the artifact as soon as we have it
      - name: Archive Artifacts for ${{ github.event.inputs.chain }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.chain }}-runtime
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ github.event.inputs.chain }}-srtool-digest.json
            ${{ github.event.inputs.chain }}-metadata.json
            ${{ github.event.inputs.chain }}-metadata.txt
            ${{ github.event.inputs.chain }}-subwam-info.json
            ${{ github.event.inputs.chain }}-subwam-info.txt
            ${{ github.event.inputs.chain }}-diff.txt

      # We now get extra information thanks to subwasm
      - name: Install subwasm
        run: |
          wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          subwasm --version
      - name: Show Runtime information
        shell: bash
        run: |
          subwasm info ${{ steps.srtool_build.outputs.wasm }}
          subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }}
          subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ github.event.inputs.chain }}-info.json
          subwasm --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ github.event.inputs.chain }}-compressed-info.json
      - name: Extract the metadata
        shell: bash
        run: |
          subwasm meta ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > ${{ github.event.inputs.chain }}-metadata.json
      - name: Check the metadata diff
        shell: bash
        # the following subwasm call will error for chains that are not known and/or live, that includes shell for instance
        run: |
          subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ github.event.inputs.chain }} || \
            echo "Subwasm call failed, check the logs. This is likely because ${{ github.event.inputs.chain }} is not known by subwasm" | \
            tee ${{ github.event.inputs.chain }}-diff.txt
      - name: Archive Subwasm results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.chain }}-runtime
          path: |
            ${{ github.event.inputs.chain }}-info.json
            ${{ github.event.inputs.chain }}-compressed-info.json
            ${{ github.event.inputs.chain }}-metadata.json
            ${{ github.event.inputs.chain }}-diff.txt
